### ISSUE TITLE
Set up data base

### ISSUE THREAD

**Issue by BulldogBiggs** [NylanW1/ThePound#1]
We need a database to store user information and post data.

**Comment by codepathreview** [comment]
Looks like you did not implement the following user story/ies:

- Updated group info in the Course Portal: Group Name + App Description.

We encourage everyone to complete all the [required user stories](https://courses.codepath.org/snippets/android_university/grading) for each assignment to demonstrate topic understanding. While we **won't** be regrading this submission anymore, we hope you try to complete all required user stories [indicated here](https://courses.codepath.org/snippets/android_university/grading) or on the Course Portal assignment tab for **future assignments**. 
/cc @codepathreview

**Comment by codepathreview** [comment]
Looks like you did not implement the following user story/ies:

- Completed user stories checked-off in README
- Gifs created to show build progress and added to README

We encourage everyone to complete all the [required user stories](https://courses.codepath.org/snippets/android_university/grading) for each assignment to demonstrate topic understanding. While we **won't** be regrading this submission anymore, we hope you try to complete all required user stories [indicated here](https://courses.codepath.org/snippets/android_university/grading) or on the Course Portal assignment tab for **future assignments**. 
/cc @codepathreview
