### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [NylanW1/ThePound#14]
Looks like you did not implement the following user story/ies:

 * Completed user stories checked-off in README
 * Sprint planned for next week -- Issues created, assigned & added to project board. *The To Do Column in your Project is empty.*

We encourage everyone to complete all the required user stories for each assignment to demonstrate topic understanding. While we won't be regrading this submission anymore, we hope you try to complete all required user stories indicated here or on the Course Portal assignment tab for **future assignments.**

**Comment by NylanW1** [comment]
I'm confused, the readme was updated to reflect the stories that have been completed to this point. Should all the stories not be included in the readme until they are complete? I also don't see in the directions on codepath where it says something has to be in each column of the project board. I would like for units 10 and 11 to be re-evaluated.
